### ISSUE TITLE
Application Exception message

### ISSUE THREAD

**Issue by steelers4582** [coldbox-modules/cbmessagebox#1]
I get the following Exception message after installing cbmessagebox.  It still works properly but I noticed this just now.   Appears to be happening with the flash inject.

Exceptions
11:16:01.001 - Application Exception - in <generated> : line 1
        The method getflash was not found in component C:/ColdFusion10/cfusion/wwwroot/myapp/modules/cbmessagebox/models/MessageBox.cfc.

**Comment by lmajano** [comment]
Where is this being called from?

**Comment by steelers4582** [comment]
My request decorator located in my models folder:

myapp
- models
       requestDecorator.cfc

component entityname="requestDecorator" output="false"
extends="coldbox.system.web.context.RequestContextDecorator" {

public void function configure(){
var wirebox = instance.controller.getWirebox();
var logbox = instance.controller.getLogBox();
 var rc = getRequestContext().getCollection();
var prc = getRequestContext().getCollection(private = true);
 prc.sessionStore = wirebox.getInstance('SessionStorage@cbstorages');
                prc.clientStore =
wirebox.getInstance('ClientStorage@cbstorages');
                prc.msg = wirebox.getInstance('messagebox@cbmessagebox');

```
prc.log = logbox.getRootLogger();
prc.helpDeskNo = instance.controller.getSetting("helpDeskNo");
```

}

}

cbmessagebox folder is located in my applications modules folder:

myapp
- modules
  - cbmessagebox

"ColdBox Request Structures" on my debug info shows the "msg" private
collection as it should and I am able to modify and display the message
through the app just fine.

**Comment by lmajano** [comment]
I still don't see where the `getFlash()` is coming from

**Comment by steelers4582** [comment]
It's located in cbmessagebox/models/MessageBox.cfc line 21...



<cfproperty name="flash" inject="coldbox:flash">

Maybe just another instance in the way/location I am using
getInstance('messagebox@cbmessagebox')?

**Comment by lmajano** [comment]
Hmm, it might be that you are trying to use the message box when the framework is still trying to boot up.

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.comP/F: 1-888-557-8057

Direct: (909) 248-3408

ColdBox Platform: http://www.coldbox.org

ContentBox Platform: http://www.gocontentbox.org

Linked In: http://www.linkedin.com/pub/3/731/483

Social: twitter.com/ortussolutions | twitter.com/coldbox | twitter.com/lmajano | twitter.com/gocontentbox
