### ISSUE TITLE
Feature request - Configurable message types

### ISSUE THREAD

**Issue by chopki** [coldbox-modules/cbmessagebox#6]
At the moment this is a useful module but it lacks configuration: if i want a "success" message (which i am sure is not too edge case) i cannot use this, i must first extend it which seems a bit overkill for something as simple as a green success message (note: i want all other types built in as well).

It would make more sense (to me) to have an array of extra message types that can be accepted in the coldbox.cfc messagebox config. Obviously i would also have to update my custom view for messgaebox to apply the correct styles for the new types but that's fine by me.

Implementation wise i cant see anything too horrible with this other than having to use SetMessage("myNewType" .. ) over messagebox.myNewType( "message" ) which i would be fine with. Assuming there could be issues if you used onMissingMethod with any random function name the same as any custom type.

Just wanted to check this runs with the direction you want to take this module before making the changes and submitting as a PR (does not look to be a massive task).

**Comment by jclausen** [comment]
@chopki :  

There's no need to extend the module to customize the message.  You just need to create your own template and configure it as the template in your `config/Coldbox.cfc`.  

You'll notice there's no strong typing in the core `MessageBox.cfc`  methods, so you can pass a complex struct to the `info()` method as the `message` argument, if you wish - as long as your template knows what to do with it.

Template example, using Bootstrap:

**Configuration:**

```
messagebox = {
			template="/views/MessageBox.cfm"
		};
```

**Invocation, using a struct as the message argument:**

```
messagebox.info( { "icon" : "check-circle", "class" : "success", "content" : "Yay! Success!" } );
```

**MessageBox.cfm**

```
<cfoutput>
<cfoutput>
	<div class="messagebox-alert messagebox-#msgStruct.type# row alert alert-#msgStruct.message.class#" style="font-size: 1.1em; margin-top: -18px">
		<div class="col-xs-1 col-xs-offset-2 pull-left" style="text-align:center;">
			<i class="fa fa-#msgStruct.message.icon# fa-lg" style="margin-top: 8%"></i>
		</div>
		<div class="col-xs-9 pull-right">#msgStruct.message.content#</div>
		<div class="clearfix"></div>
	</div>
</cfoutput>
```

**Comment by chopki** [comment]
Cool i completely glossed over that - thanks for pointing that out. 

Though looking at your example its seems overkill to create separate struct containing all of that every time i want to pass just a string. It would still seem simpler to me to be able to have this kind of thing configurable and just use setMessage("success", "new message"). 

Also if there was more configuration i could very simply change the styles used for the built in message types there, which to me seems nicer than having to override the template - seems a nicer way of handling it to me.

**Comment by jclausen** [comment]
It is, maybe, a bit of overkill.  You could certainly modify the template to accept a string argument as the `msgStruct.message` and param the defaults for additional information.   The implicit methods of Messagebox are based on the the middle-tier log levels of the log4j hierarchy: `INFO`, `WARN`, `ERROR`.

Adding a `success()` method would break that pattern.  That said, I'm _not_ opposed to adding another method.  All it would really do is add an additional `msgStruct.type` variable to the template, which already has the capability to be customized to the application.

**Comment by bdw429s** [comment]
I would be in favor of modifying the core module to have a `success` type and to allow for an array of messages.  I used this for years back at my old job and we just ended up creating our own version of it that had success and did an array so we could have a bunch of validation messages and loop over each one.  That may require a major version bump though.

**Comment by gpickin** [comment]
This has been added to the core, closing since its done now.
